version: "3.8"

services:
  bitcoind:
    image: lncm/bitcoind:v24.0@sha256:db19fe46f30acd3854f4f0d239278137d828ce3728f925c8d92faaab1ba8556a
    command:
      - -${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcauth=user:2ba7454abfebe5d5766bda9d93c9e633$df4fc916583a0089daf1c4b33332651df281ba08a4750f8b4c118b13a50aed7c
    restart: on-failure
    volumes:
      - ${PWD}/data/bitcoin:/root/.bitcoin
    networks:
      networkcln:
        ipv4_address: ${APP_BITCOIN_NODE_IP}

  lightningd:
    image: elementsproject/lightningd:v22.11.1@sha256:14f1a7937f9692184e46ab6245ed51ed86262d208e81fd5ec5f0339ac5bf8096
    command:
      - --bitcoin-rpcconnect=${APP_BITCOIN_NODE_IP}
      - --bitcoin-rpcuser=${APP_BITCOIN_RPC_USER}
      - --bitcoin-rpcpassword=${APP_BITCOIN_RPC_PASS}
      - --bind-addr=${APP_CORE_LIGHTNING_DAEMON_IP}:9735
      - --network=${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - --database-upgrade=true
      - --grpc-port=${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      - --experimental-websocket-port=${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
      - --experimental-offers
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd:/root/.lightning
    networks:
      networkcln:
        ipv4_address: ${APP_CORE_LIGHTNING_DAEMON_IP}

  application:
    build:
      dockerfile: ./Dockerfile
      context: ./
    # image: ghcr.io/elementsproject/cln-application:0.0.1@sha256:631f765969324aaf3b26958d91f47626570092bd2babfd4189d5d6f46918a5ba
    depends_on:
      - bitcoind
      - lightningd
    environment:
      APP_CORE_LIGHTNING_PORT: ${APP_CORE_LIGHTNING_PORT}
      APP_CORE_LIGHTNING_DAEMON_IP: ${APP_CORE_LIGHTNING_DAEMON_IP}
      APP_CORE_LIGHTNING_BITCOIN_NETWORK: ${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      APP_CORE_LIGHTNING_IP: ${APP_CORE_LIGHTNING_IP}
      APP_CORE_LIGHTNING_DAEMON_GRPC_PORT: ${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      APP_CORE_LIGHTNING_REST_PORT: ${APP_CORE_LIGHTNING_REST_PORT}
      APP_CORE_LIGHTNING_WEBSOCKET_PORT: ${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
      APP_CORE_LIGHTNING_REST_CERT_DIR: ${APP_CORE_LIGHTNING_REST_CERT_DIR}
      APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE: http://${APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE}
      APP_CORE_LIGHTNING_COMMANDO_ENV_DIR: ${APP_CORE_LIGHTNING_COMMANDO_ENV_DIR}
      APP_CONFIG_DIR: ${APP_CONFIG_DIR}
      APP_MODE: "production"
      LOCAL_HOST: http://${DEVICE_DOMAIN_NAME}
      CA_CERT: /root/.lightning/bitcoin/ca.pem
      CLIENT_KEY: /root/.lightning/bitcoin/client-key.pem
      CLIENT_CERT: /root/.lightning/bitcoin/client.pem
    command: npm run start
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd:/root/.lightning
      - ${PWD}/data/c-lightning-rest/certs:/c-lightning-rest/certs
      - ${PWD}/data/app:/data/app
    ports:
      - "${APP_CORE_LIGHTNING_PORT}:${APP_CORE_LIGHTNING_PORT}"
    networks:
      networkcln:
        ipv4_address: ${APP_CORE_LIGHTNING_IP}

networks:
  networkcln:
    driver: bridge
    ipam:
      config:
        - subnet: 170.21.22.0/16
          gateway: 170.21.22.0
