version: "3.8"

services:
  bitcoind:
    image: lncm/bitcoind:v24.0@sha256:db19fe46f30acd3854f4f0d239278137d828ce3728f925c8d92faaab1ba8556a
    command:
      - -${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - -fallbackfee=0.0002
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcauth=user:d58ddb294b3a3812ff5fee50d6f24b29$19212992730deeaf6e596d471260a966b011a00446d45b193c94e79c4f4a1266
    restart: on-failure
    volumes:
      - ${PWD}/data/bitcoin:/root/.bitcoin
    networks:
      networkcln:
        ipv4_address: ${APP_BITCOIN_NODE_IP}

  lightningd:
    image: elementsproject/lightningd:v22.11.1@sha256:14f1a7937f9692184e46ab6245ed51ed86262d208e81fd5ec5f0339ac5bf8096
    command:
      - --bitcoin-rpcconnect=${APP_BITCOIN_NODE_IP}
      - --bitcoin-rpcuser=${APP_BITCOIN_RPC_USER}
      - --bitcoin-rpcpassword=${APP_BITCOIN_RPC_PASS}
      - --bind-addr=${APP_CORE_LIGHTNING_DAEMON_IP}:9735
      - --network=${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - --database-upgrade=true
      - --grpc-port=${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      - --experimental-websocket-port=${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
      - --experimental-offers
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd:/root/.lightning
    ports:
      - ${APP_CORE_LIGHTNING_WEBSOCKET_PORT}:${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
    networks:
      networkcln:
        ipv4_address: ${APP_CORE_LIGHTNING_DAEMON_IP}

  application:
    build:
      dockerfile: ./Dockerfile
      context: ./
    # image: ghcr.io/elementsproject/cln-application:0.0.2@sha256:6188255f56a679b9e5785036ab50ad1d2c869568c2f29d07f0c482917c7442e9
    depends_on:
      - bitcoind
      - lightningd
    environment:
      APP_CORE_LIGHTNING_PORT: ${APP_CORE_LIGHTNING_PORT}
      APP_CORE_LIGHTNING_DAEMON_IP: ${APP_CORE_LIGHTNING_DAEMON_IP}
      APP_CORE_LIGHTNING_BITCOIN_NETWORK: ${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      APP_CORE_LIGHTNING_IP: ${APP_CORE_LIGHTNING_IP}
      APP_CORE_LIGHTNING_DAEMON_GRPC_PORT: ${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      APP_CORE_LIGHTNING_REST_PORT: ${APP_CORE_LIGHTNING_REST_PORT}
      APP_CORE_LIGHTNING_WEBSOCKET_PORT: ${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
      APP_CORE_LIGHTNING_REST_CERT_DIR: ${APP_CORE_LIGHTNING_REST_CERT_DIR}
      APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE: http://${APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE}
      CORE_LIGHTNING_PATH: ${CORE_LIGHTNING_PATH}
      COMMANDO_CONFIG: ${COMMANDO_CONFIG}
      APP_CONFIG_DIR: ${APP_CONFIG_DIR}
      APP_MODE: "production"
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      LOCAL_HOST: http://${DEVICE_DOMAIN_NAME}
      CA_CERT: /root/.lightning/bitcoin/ca.pem
      CLIENT_KEY: /root/.lightning/bitcoin/client-key.pem
      CLIENT_CERT: /root/.lightning/bitcoin/client.pem
    command: npm run start
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd:/root/.lightning
      - ${PWD}/data/c-lightning-rest/certs:/c-lightning-rest/certs
      - ${PWD}/data/app:/data/app
    ports:
      - "${APP_CORE_LIGHTNING_PORT}:${APP_CORE_LIGHTNING_PORT}"
    networks:
      networkcln:
        ipv4_address: ${APP_CORE_LIGHTNING_IP}

networks:
  networkcln:
    driver: bridge
    ipam:
      config:
        - subnet: 170.21.22.0/16
          gateway: 170.21.22.0
