version: "3.8"

services:
  bitcoind:
    image: lncm/bitcoind:v24.0@sha256:db19fe46f30acd3854f4f0d239278137d828ce3728f925c8d92faaab1ba8556a
    env_file: .env
    command:
      - -${CLN_BITCOIN_NETWORK}
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcauth=umbrel:5071d8b3ba93e53e414446ff9f1b7d7b$$375e9731abd2cd2c2c44d2327ec19f4f2644256fdeaf4fc5229bf98b778aafec
    restart: on-failure
    volumes:
      - ${PWD}/data/bitcoin:/root/.bitcoin
    networks:
      networkcln:
        ipv4_address: ${BITCOIN_NODE_IP}

  lightning:
    image: elementsproject/lightningd:v22.11.1@sha256:14f1a7937f9692184e46ab6245ed51ed86262d208e81fd5ec5f0339ac5bf8096
    env_file: .env
    command: --bitcoin-rpcconnect=${BITCOIN_NODE_IP} --bitcoin-rpcuser=${BITCOIN_RPC_USER} --bitcoin-rpcpassword=${BITCOIN_RPC_PASS} --bind-addr=${CLN_DAEMON_IP}:9735 --network=${CLN_BITCOIN_NETWORK} --grpc-port=${CLN_DAEMON_GRPC_PORT} --experimental-websocket-port=${CLN_DAEMON_WS_PORT} --experimental-offers
    restart: on-failure
    volumes:
      - ${PWD}/data/lightning:/root/.lightning
    networks:
      networkcln:
        ipv4_address: ${CLN_DAEMON_IP}

  application:
    build:
      dockerfile: ./Dockerfile
      context: ./
    # image: shahanafarooqui/umbrel-core-lightning@sha256:3b040a754e9e1daef492393849b946dc2c66682e1fcdf537bb9f8ddcdec1fd7b
    depends_on:
      - bitcoind
      - lightning
    env_file: .env
    command: npm run start
    restart: on-failure
    volumes:
      - ${PWD}/data/lightning:/root/.lightning
      - ${PWD}/data/c-lightning-rest:/data/c-lightning-rest
      - ${PWD}/data/app:/data/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      networkcln:
        ipv4_address: ${APP_IP}

networks:
  networkcln:
    driver: bridge
    ipam:
      config:
        - subnet: 170.21.21.0/16
          gateway: 170.21.21.0
